
name: start

on: [push]

jobs:
  build:
   
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v
      - with:
        python-version: '3.9'
        architecture: 'x64'
      - name: setup python4
        run: python my_script.py
      

