
name: start

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
   
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Setup Python
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      
      with:
        python-version: ${{ matrix.python-version }}

    - run: python my_script.py
      

